[package]
name = "cas"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cas"

[dependencies]
anyhow = "1.0.100"
blake3 = "1.8.2"
clap = { version = "4.5.53", features = ["derive"] }
thiserror = "2.0.17"
